---
- name: Deploy to Tomcat
  hosts: web
  become: yes

  tasks:

    - name: Copy WAR file to Tomcat
      copy:
        src: target/maven-webapp.war
        dest: /opt/tomcat/webapps/maven-webapp.war

    - name: Stop Tomcat
      shell: /opt/tomcat/bin/shutdown.sh
      ignore_errors: yes

    - name: Start Tomcat
      shell: /opt/tomcat/bin/startup.sh
